name: Build and Deploy Pelican Site

# This workflow runs when you push to the 'source' branch
on:
  push:
    branches:
      - source

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source branch
        uses: actions/checkout@v4
        with:
          ref: source # Explicitly checks out the source branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the site with Pelican
        run: pelican content -s publishconf.py

      - name: Deploy to master branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: master # This is the critical line
          cname: ignorantforager.com
